### ISSUE TITLE
Is Redis Required?

### ISSUE THREAD

**Issue by danielflippance** [ecto/lunr#7]
The README.md implies that Redis is required "When a PUT command is issued against lunrd, it is put into a FIFO queue (stored in Redis)." 

However the config file comments seem to imply Redis queueing can be disabled by setting the config to false:  "queue": false,  // use Redis as a FIFO queue for PUT commands?

Can you clarify if Redis is required.

**Comment by ecto** [comment]
redis is not required. however, i would discourage use of this library as it is not complete nor supported.
